### ISSUE TITLE
AreaChart not binding hide-hover

### ISSUE THREAD

**Issue by ansisblodnieks** [bbonnin/vue-morris-example#1]
Created 2 charts - bar chart & area chart. When I set the option hide-hover, the BarChart includes this param in the options, but the AreaChart ignores it.

<AreaChart
                    :xkey="chart.xkey"
                    :ykeys="chart.ykeys"
                    :labels="chart.labels"
                    :id="chart.id"
                    :data='chart.data'
                    :line-colors='chart.lineColors'
                    grid="true"
                    grid-text-weight="bold"
                    resize="false"
                    :hide-hover='chart.hideHover'
            />

<BarChart
                    :xkey="chart.xkey"
                    :ykeys="chart.ykeys"
                    :labels="chart.labels"
                    :id="chart.id"
                    :data='chart.data'
                    :bar-colors='chart.lineColors'
                    grid="true"
                    grid-text-weight="bold"
                    resize="false"
                    :hide-hover='chart.hideHover'
            />

**Comment by bbonnin** [comment]
I have forgotten this option for area and line charts. It has been added in vue-morris v0.0.7.
Thank you !
